// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamUi5RZWCgZ5AL8VSMS0i_1VfOBjaG7s',
    appId: '1:551027771726:web:8a33d36ec5543ad0bbb61f',
    messagingSenderId: '551027771726',
    projectId: 'e-commerce-flutter-cours-cbbba',
    authDomain: 'e-commerce-flutter-cours-cbbba.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-cours-cbbba.firebasestorage.app',
    measurementId: 'G-HM0DC3VB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvB18NllXJHc_frKz4hkdzyREmEptQIVk',
    appId: '1:551027771726:android:148b2c810c4a04f8bbb61f',
    messagingSenderId: '551027771726',
    projectId: 'e-commerce-flutter-cours-cbbba',
    storageBucket: 'e-commerce-flutter-cours-cbbba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5WPYQMav5lgspn5dWF7NSS6d48xHcSag',
    appId: '1:551027771726:ios:14d99428bc953465bbb61f',
    messagingSenderId: '551027771726',
    projectId: 'e-commerce-flutter-cours-cbbba',
    storageBucket: 'e-commerce-flutter-cours-cbbba.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5WPYQMav5lgspn5dWF7NSS6d48xHcSag',
    appId: '1:551027771726:ios:14d99428bc953465bbb61f',
    messagingSenderId: '551027771726',
    projectId: 'e-commerce-flutter-cours-cbbba',
    storageBucket: 'e-commerce-flutter-cours-cbbba.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBamUi5RZWCgZ5AL8VSMS0i_1VfOBjaG7s',
    appId: '1:551027771726:web:fad9cd12df9d2eabbbb61f',
    messagingSenderId: '551027771726',
    projectId: 'e-commerce-flutter-cours-cbbba',
    authDomain: 'e-commerce-flutter-cours-cbbba.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-cours-cbbba.firebasestorage.app',
    measurementId: 'G-EJ0N0LK3C7',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBamUi5RZWCgZ5AL8VSMS0i_1VfOBjaG7s',
    appId: '1:551027771726:web:8a33d36ec5543ad0bbb61f',
    messagingSenderId: '551027771726',
    projectId: 'e-commerce-flutter-cours-cbbba',
    authDomain: 'e-commerce-flutter-cours-cbbba.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-cours-cbbba.firebasestorage.app',
    measurementId: 'G-HM0DC3VB8P',
  );
}
